### ISSUE TITLE
[META] GTK4 progress

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#109]
# Current state

The GTK4 migration has been going on in the background for quite a while now. After  the GNOME team decided to reMove a lot of useful functionality such as properly positioning windows, a lot of this had to be reimplemented manually for GTK4. This seems to be pretty much done, at least the basics. Doing those X11 spacific things, an implementation of `_NET_WM_STRUT` has also been realized in the gtk4 branch.
As a result of GTK removing a lot of the display-backand specific functionality, MacOS support is currently worse than ever, which should be improved.

As described in the closing comment on #10, GTK4 removed the possibility of using wlr-layer-shell to render Eww on wayland. This means that on wayland, eww will not be able to position its widgets itself - that will have to be done from the wayland compositors side.

Given that GTK4 is still very new, it isn't actually packaged everywhere yet. As long as GTK4 is not available in at least a couple of the more popular distributions that eww users may be using, gtk4 will not be merged into master. Once it does get merged, a short guide / link on how to build GTK4 if it's not available will have to be added to the Readme and documentation.

# Why even GTK4
Reading all of those issues introduced b. Gtk4, understandably the question as to _why_ a migration should still be done arises. The answer to that has three parts:

- *staying up-to-date*: Gtk4 will be the standard at some point. Migrating now, when there are only a few active users, and the migration is still relatively easy is prefferable to doing it later, when more things and people depend on semantics changed by the upgrade, and when more code would have to be adjusted.
- *GTK4 simplifies widgets*: In GTK3, the widget structure of some widgets such as sliders or treeviews is somewhere between weird and downright stupid and cryptic. GTK4 cleans those up in some areas, which promises to make styling those widgets more intuitive and easy.
- *shaders*: GTK4 adds support for using arbitrary GL shaders on widgets. This has multiple benefits: It allows eww to provide users with the ability to render and apply arbitrary shaders to their widgets, making the possibilities of what is achievable with eww nearly infinite. Additionally, it allows eww to provide some shader based options out of the box, allowing for things  such as glowing or wobbly widgets without much effort. This is fun, and eww should be fun.

# What's left
With the current GTK4 branch, which should already be usable for X11 users, some things are still missing until it can be merged into master:
- [ ] more testing. Currently, the reimplementations of gtk3 features haven't all been tested sufficiently, so a bit more confidence in them should be gained first
- [ ] implementing shader support. While predefined shaders aren't a requirement for this, support for user defined shaders should be implemented, as this is one of the key benefits of GTK4
- [ ] adjusting documentation. The docs need to be adjusted to link to gtk4 resources and some reference regarding building GTK4 has to be added.

**Comment by Axarva** [comment]
*Sad Gentoo user noises*

**Comment by undefinedDarkness** [comment]
With shaders, eww will finally be deserving of wacky in the title hopefully

**Comment by elkowar** [comment]
Compiling GTK really isn't all that bad, it takes like 2 minutes on a reasonably high end PC, so it'll not be all that bad even on low-end machines

**Comment by elkowar** [comment]
# Update

Gtk4 turns out to be _really_ unstable currently, also noticably slower.
As some other things that I want to implement require sizable refactors of other parts of the code, and I _really_ don't want to maintain two codebases, the GTK4 migration will be stopped, for now.

It's really sad, as the GTK4 stuff could have been awesome. But, given all of the issues that came up, waiting for gtk4 to be ready, stable and for the GNOME team to **fix their shit** regarding the removed APIs and regarding wayland support will make a lot of things a lot less stressful.

For those of you who where waiting for wobbly widgets,... hope is not lost, it's just going to take a bit longer than initially expected.

**Comment by ggaast** [comment]
how about now? is it not the right time to implement gtk4?
