### ISSUE TITLE
[BUG] eww reload randomly cause damage tracking issues on wayland

### ISSUE THREAD

**Issue by HeavyRain266** [elkowar/eww#235]
## Checklist before submitting an issue
- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

## Describe the bug
Whne you open any widget (in my case example bar) then start editing and reload it with `eww reload` then every view and widget itself randomly goes black for seconds and everything is noticable redrawn on screen. Already tried with my compositor (vulkan), kiwmi and river (opengl) and in all of them there is same effect. It's happening because GTK wasn't designed to use with layershell and it can also be caused by gtk-layer-shell...

## Reproducing the issue
Log into any compositor with implemented damage tracking, run `eww daemon`, open your widgets with `:exclusive` enabled, then try changing any contend and `eww reload` them (noticed with example bar)

## Expected behaviour
Eww should request damage on reload then this would cause redrawning only widget and not everything.

**Comment by snakedye** [comment]
That's because the widget's surface is destroyed not damaged. I'm fairly sure it's the same on X too.

**Comment by elkowar** [comment]
Eww reload completely re-opens the window, a short flash is thus to be expected. I don't think there's any bug here, is there? Reloading the config should only happen during configuration, so in actual use that flash doesn't occurr
