### ISSUE TITLE
Tracking issue for state rework

### ISSUE THREAD

**Issue by elkowar** [elkowar/eww#326]
Ewws state management has been an ugly point of the codebase for a while. Additionally, the current architecture is the cause of several limitations, such as not being able to implement #324, as well as bugs such as #325.
Thus, a rework of the state architecture is necessary.

I've been thinking about how to clean this up and structure this differently for a while now.
After a lot of thinking, I came up with an approach that I think will work well!

This issue exists mainly as a point to link to, as well as collecting some information about the progress.

## Approach
A short summary of the new approach for those interested:
Instead of linking state directly into a single-layer state-store at the root, the new architecture will represent the state as a tree of nested scopes, which is much closer to what the state actually represents. That graph structure allows for dynamically adding and removing event listeners and changing the structure of scopes dynamically.

## Current state
- [x] Come up with basic implementation concept
- [x] Implement scope tree
- [x] migrate widget generation to use new scope tree
- [x] completely remove old remaining `EwwState` code
- [x] Test everything
